package com.taobao.fario.server.service;

// Generated 2012-6-12 17:01:23 by Hibernate Tools 3.4.0.CR1

/**
 * Locationhistory generated by hbm2java
 */
public class Locationhistory implements java.io.Serializable {

	private LocationhistoryId id;
	private UserInfo userInfo;

	public Locationhistory() {
	}

	public Locationhistory(LocationhistoryId id) {
		this.id = id;
	}

	public Locationhistory(LocationhistoryId id, UserInfo userInfo) {
		this.id = id;
		this.userInfo = userInfo;
	}

	public LocationhistoryId getId() {
		return this.id;
	}

	public void setId(LocationhistoryId id) {
		this.id = id;
	}

	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

}
